# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jafri/eosio.contracts/contracts

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jafri/eosio.contracts/contracts

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/jafri/eosio.contracts/contracts && $(CMAKE_COMMAND) -E cmake_progress_start /Users/jafri/eosio.contracts/contracts/CMakeFiles /Users/jafri/eosio.contracts/contracts/vest/CMakeFiles/progress.marks
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 vest/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jafri/eosio.contracts/contracts/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 vest/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 vest/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 vest/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/jafri/eosio.contracts/contracts && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
vest/CMakeFiles/vest.dir/rule:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 vest/CMakeFiles/vest.dir/rule
.PHONY : vest/CMakeFiles/vest.dir/rule

# Convenience name for target.
vest: vest/CMakeFiles/vest.dir/rule

.PHONY : vest

# fast build rule for target.
vest/fast:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/build
.PHONY : vest/fast

src/escrow.obj: src/escrow.cpp.obj

.PHONY : src/escrow.obj

# target to build an object file
src/escrow.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/escrow.cpp.obj
.PHONY : src/escrow.cpp.obj

src/escrow.i: src/escrow.cpp.i

.PHONY : src/escrow.i

# target to preprocess a source file
src/escrow.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/escrow.cpp.i
.PHONY : src/escrow.cpp.i

src/escrow.s: src/escrow.cpp.s

.PHONY : src/escrow.s

# target to generate assembly for a file
src/escrow.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/escrow.cpp.s
.PHONY : src/escrow.cpp.s

src/transfer.obj: src/transfer.cpp.obj

.PHONY : src/transfer.obj

# target to build an object file
src/transfer.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/transfer.cpp.obj
.PHONY : src/transfer.cpp.obj

src/transfer.i: src/transfer.cpp.i

.PHONY : src/transfer.i

# target to preprocess a source file
src/transfer.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/transfer.cpp.i
.PHONY : src/transfer.cpp.i

src/transfer.s: src/transfer.cpp.s

.PHONY : src/transfer.s

# target to generate assembly for a file
src/transfer.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/transfer.cpp.s
.PHONY : src/transfer.cpp.s

src/utils.obj: src/utils.cpp.obj

.PHONY : src/utils.obj

# target to build an object file
src/utils.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/utils.cpp.obj
.PHONY : src/utils.cpp.obj

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/vest.obj: src/vest.cpp.obj

.PHONY : src/vest.obj

# target to build an object file
src/vest.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/vest.cpp.obj
.PHONY : src/vest.cpp.obj

src/vest.i: src/vest.cpp.i

.PHONY : src/vest.i

# target to preprocess a source file
src/vest.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/vest.cpp.i
.PHONY : src/vest.cpp.i

src/vest.s: src/vest.cpp.s

.PHONY : src/vest.s

# target to generate assembly for a file
src/vest.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f vest/CMakeFiles/vest.dir/build.make vest/CMakeFiles/vest.dir/src/vest.cpp.s
.PHONY : src/vest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... vest"
	@echo "... src/escrow.obj"
	@echo "... src/escrow.i"
	@echo "... src/escrow.s"
	@echo "... src/transfer.obj"
	@echo "... src/transfer.i"
	@echo "... src/transfer.s"
	@echo "... src/utils.obj"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/vest.obj"
	@echo "... src/vest.i"
	@echo "... src/vest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/jafri/eosio.contracts/contracts && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

